### ISSUE TITLE
`scripts:lint` should be the last gulp task to run

### ISSUE THREAD

**Issue by cmalven** [onedesign/generator-one-base#11]
Right now our `scripts:lint` task is dependent on `scripts:bundle` (which it doesn't really need to be) and runs as one of the first gulp tasks. This means that on the initial run of `gulp` – and on any future changes to javascript files – the results of the `scripts:lint` task are likely to be buried in the terminal, reducing the chances that they'll be seen and addressed.

Making this `scripts:lint` task one of the last things to run would probably make it more effective.

**Comment by brianjhanson** [comment]
I was planning on trying to figure out a way to use the eslint html output to throw linting errors into the browser rather than the terminal (which is rarely the focused window for me). I think that would help. 

If we want to get real serious, we could probably add a pre-commit hook that doesn't let you commit with eslint errors.

**Comment by cmalven** [comment]
That's funny that you bring that up, because I have a little branch locally that does exactly that.

**Comment by cmalven** [comment]
By "exactly that" I mean displays ESLint, Webpack Bundle, and Sass compilation errors in the browser (in addition to the terminal).
