### ISSUE TITLE
Remove AWS Imager configuration

### ISSUE THREAD

**Issue by brianjhanson** [onedesign/generator-one-base#56]
Located over here https://github.com/onedesign/generator-one-base/blob/master/generators/craft/templates/craft/config/imager.php#L13

This screws things up if your _not_ using AWS and is pretty hard to track down (looks like a permissions issue)

**Comment by cmalven** [comment]
So, ideally we would _only_ include this if the `imager` plugin was selected for installation, right?

**Comment by cmalven** [comment]
(it's not clear from the comment in that code, but all of those settings are specifically for Imager, not AWS)

**Comment by cmalven** [comment]
Nevermind, I completely misunderstood. Seems like you're probably going to have to add _something_ to this file for config, right? Instead of getting rid of it, could we comment it out and add (also commented out) lines for alternate configs? I just don't want people to have to track down the necessary config options every time they run this generator.
