### ISSUE TITLE
Running imagemin on gulp build only

### ISSUE THREAD

**Issue by collinjoyce** [onedesign/generator-one-base#70]
Longtime lurker, first-time contributor 😄 

In my recent gulp setups, I've been taking the `image-min` task out of the default `images.js` that runs via the base gulp task. I've found this to not only take too long once you have a lot of images built up in your `/src/images/` folder, but it also doesn't play nicely with browsersync.

How would everyone feel about moving the `image-min` task to the `gulp build` task only? It would mean breaking out the `images.js` into two tasks, but I think it's worth it.

**Comment by cmalven** [comment]
I've noticed this too, but alwayys been hesitant to do it just because I felt the initially long gulp task wasn't quite bad enough to require people to run an additional gulp task.

Another option would be to make the images task the last one that runs, since nothing else is actually dependent on it. It could even run after browsersync so you wouldn't even have to really know it was running.

**Comment by brianjhanson** [comment]
I'm cool with either but probably lean slightly towards just running it on build. Since Buddy is always running `build` we shouldn't have to worry about un-compressed images making it anywhere live.

Do you have an example of how you split it up? Are you thinking an `images:copy` task that just moves them from `src/images` over to `public/dist`? Then another that compresses them on the way? Or would you slice it up a different way?

**Comment by cmalven** [comment]
We don't have to do this, but just to show how easy it would be to update the gulp setup to run `images` after everything else is finished:

https://github.com/onedesign/generator-one-base/compare/gulp-images-last?expand=1

**Comment by cmalven** [comment]
I'm going to close this given the recently merged change that processes all images in the background after all other tasks are finished (and only processes changed images). If people continue to have issues with this please open another issue.
