### ISSUE TITLE
Merge changes from this repo into existing projects

### ISSUE THREAD

**Issue by mkornatz** [onedesign/generator-one-base#76]
As we're going through and making improvements to our build jobs and things, it would be great if we can pull them into our existing projects in order to keep things consistent and use the improvements we're making.

Is there an easy way we can pull changes into existing projects without running into conflicts in the existing repos? Or, are we destined to make the changes manually in that regard? Maybe the generator could take a path to an existing project and update the build scripts?

**Comment by cmalven** [comment]
@mkornatz We're making some amount of progress in being able to run this for existing projects to update them: for instance the change I made to the `gulp` sub-generator this weekend allows you to run `yo one-base:gulp --force` in the directory for an existing gulp project and it will replace the gulp setup in place.

This is still a partially manual process, but I think in a good way: after you run the above, you'll be able to see all of the changed files in your git status, and you can discard/add individual line changes as necessary. I tried this for an existing project this weekend and it worked really well, made it super clear exactly what running the generator again had changed in the gulp setup. I think this is definitely good enough though, requires less than 5-10 minutes per project typically.

This only works with the gulp-related stuff right now, though, but wouldn't be too hard to continue to refactor the generator so that the same type of thing could apply to general project setup and craft stuff as well. Would love to have some help with PRs for that stuff!

**Comment by cmalven** [comment]
Closing this since it's a general dev todo and not really the responsibility of the generator. The generator includes instructions on how to run the `gulp` sub-generator on an existing project.
